/**
 * Manual test harness for services/notifications/TelegramAdminNotifier.
 *
 * Usage:
 *   node tools/test_telegram_admin_notifier.js --alert-critical
 *   node tools/test_telegram_admin_notifier.js --alert-warning
 *   node tools/test_telegram_admin_notifier.js --alert-info
 *   node tools/test_telegram_admin_notifier.js --calibration
 *
 * Requires TELEGRAM_BOT_TOKEN and ADMIN_CHAT_ID in .env.
 */

require('dotenv').config();
const path = require('path');
const { createTelegramAdminNotifier } = require(path.join('..', 'services', 'notifications', 'TelegramAdminNotifier'));

const SCENARIOS = {
    '--alert-critical': {
        label: 'Critical alert (LinkedIn auth challenge simulation)',
        run: async (notifier) =>
            notifier.sendAlert('CRITICAL', 'LinkedIn Auth Challenge Detected (test)', {
                status: 302,
                url: 'https://www.linkedin.com/voyager/api/voyagerJobsDashJobCards',
                timestamp: new Date().toISOString(),
                source: 'test-harness',
                note: 'This is a synthetic alert generated by test_telegram_admin_notifier.js',
            }),
    },
    '--alert-warning': {
        label: 'Warning alert (synthetic)',
        run: async (notifier) =>
            notifier.sendAlert('WARNING', 'DB Volume Approaching Threshold (test)', {
                currentMb: 320,
                thresholdMb: 350,
                ts: new Date().toISOString(),
            }),
    },
    '--alert-info': {
        label: 'Info alert (synthetic)',
        run: async (notifier) =>
            notifier.sendAlert('INFO', 'Synthetic informational notification', 'Plain-string details payload for variant coverage.'),
    },
    '--calibration': {
        label: 'Calibration markdown document (~50KB)',
        run: async (notifier) => {
            const header = '# Calibration Report (synthetic)\n\nGenerated at ' + new Date().toISOString() + '\n\n';
            const body = '## Section\n\n' + ('Lorem ipsum dolor sit amet, consectetur adipiscing elit. '.repeat(20) + '\n').repeat(40);
            const filler = '## Filler\n\n' + 'X'.repeat(45000) + '\n';
            const md = header + body + filler;
            console.log(`Synthetic markdown size: ${Buffer.byteLength(md, 'utf8')} bytes`);
            return notifier.sendCalibrationAlert('🚨 Test Calibration Report', md, 'volume');
        },
    },
};

async function main() {
    const flag = process.argv.slice(2).find((arg) => SCENARIOS[arg]);
    if (!flag) {
        console.error('Usage: node tools/test_telegram_admin_notifier.js [' + Object.keys(SCENARIOS).join(' | ') + ']');
        process.exitCode = 2;
        return;
    }

    const scenario = SCENARIOS[flag];
    console.log(`\n=== Scenario: ${flag} — ${scenario.label} ===`);

    if (!process.env.TELEGRAM_BOT_TOKEN || !process.env.ADMIN_CHAT_ID) {
        console.error('Missing TELEGRAM_BOT_TOKEN or ADMIN_CHAT_ID in .env');
        process.exitCode = 1;
        return;
    }

    const notifier = createTelegramAdminNotifier();
    const startedAt = Date.now();
    const ok = await scenario.run(notifier);
    const elapsedMs = Date.now() - startedAt;
    console.log(`Result: ${ok ? 'OK' : 'FAIL'} (elapsed ${elapsedMs}ms)`);
    process.exitCode = ok ? 0 : 1;
}

main().catch((err) => {
    console.error('Test harness crashed:', err && err.stack ? err.stack : err);
    process.exitCode = 1;
});
